
site_name: 💻  OddFish's CQU Computer School Vault
site_url: https://your-site.com
repo_url: https://github.com/OddFish/CQU-ComputerSchool-Vault
repo_name: CQU Computer School Vault
copyright: &copy; 2023 OddFish

theme:
  name: material
  palette:
    - scheme: dark
    - primary: green
    - accent: green
  font:
    - family: monospace
    - text: Roboto Mono
    - code: Roboto Mono
  logo: assets/odd-fish.png # Replace with your logo

nav:
  - Home: index.md
  - 📚 Course Materials:
    - 2023:
      - C Programming: c-programming.md
      - Data Structures: data-structures.md
      - Algorithms: algorithms.md
      - Operating Systems: operating-systems.md
      - Computer Networks: computer-networks.md
      - Database Systems: database-systems.md
      - Software Engineering: software-engineering.md
    - 2024:
      - [Add future courses here]
  - 💻  Tools & Resources:
    - Programming Languages:
      - Python: python.md
      - C++: cpp.md
      - Java: java.md
    - IDEs & Editors:
      - VS Code: vscode.md
      - IntelliJ IDEA: intellij-idea.md
      - Sublime Text: sublime-text.md
    - Useful Websites:
      - LeetCode: leetcode.md
      - HackerRank: hackerrank.md
      - GeeksforGeeks: geeksforgeeks.md
  - 👥  Community:
    - Discord: discord.md
    - Forum: forum.md
  - 🔒  Security:
    - Ethical Hacking: ethical-hacking.md
    - Cybersecurity: cybersecurity.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: code-block
          class: code-block
          lang: python
  - pymdownx.tabbed:
    alternate_style: true
  - pymdownx.details:
  - pymdownx.emoji:
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.tilde:
  - pymdownx.keys:
  - pymdownx.smartsymbols:
  - pymdownx.magiclink:
  - pymdownx.betterem:
  - pymdownx.mark:
  - pymdownx.progressbar:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OddFish/CQU-ComputerSchool-Vault
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-discord-server

plugins:
  - search
  - mkdocs-jupyter:
      execute: true
      timeout: 300
      allow_errors: true

